# Generated by Django 2.1.1 on 2018-09-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('G1', 'Pode ver x'), ('G2', 'Pode ver y'), ('G3', 'Pode ver z'))},
        ),
    ]
